name: lakes
description: Demonstrates building a layout for the "Lakes" app.

dependencies:
  flutter:
    sdk: flutter
  map_view:
    git:
      url: https://github.com/apptreesoftware/flutter_google_map_view
  google_sign_in: "^3.0.4"

flutter:
  uses-material-design: true
  assets:
    - images/lake.jpg






  